using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using LuminPack.SourceGenerator;
using Microsoft.CodeAnalysis;

namespace LuminPack.Code.Core;

/// <summary>
/// Emits the complete <c>LuminPackSerializer</c> entry-point class for a compilation.
/// Serialization overloads are generated per concrete formatter type (no generic
/// fallback); deserialization additionally carries a generic <c>Deserialize&lt;T&gt;</c>
/// convenience fallback that routes through the generated generic dispatch extensions.
/// The whole class is static and delegate-free: every call binds directly to the
/// generated concrete formatter extensions.
/// </summary>
public static class LuminPackSerializerGenerator
{
    private static string _extensionType = "global::LuminPack.Generated.LuminPackExtensions_";
    private static string _currentAccess = "public";

    public static string GenerateSerializerClass(Compilation compilation, MetaInfo metaInfo, ReachabilityAnalysis? reachability = null)
    {
        ITypeSymbol[] orderedTypes = LuminPackExtensionGenerator.GetOrderedFormatterTypes(compilation, reachability);
        if (orderedTypes.Length == 0)
        {
            return string.Empty;
        }
        string asm = LuminPackExtensionGenerator.SanitizeAssemblyName(compilation.AssemblyName ?? "Assembly");
        _extensionType = "global::LuminPack.Generated.LuminPackExtensions_" + asm;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using global::System;");
        sb.AppendLine("using global::System.Buffers;");
        sb.AppendLine("using global::System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using global::System.IO;");
        sb.AppendLine("using global::System.Runtime.CompilerServices;");
        sb.AppendLine("using global::System.Runtime.InteropServices;");
        sb.AppendLine("using global::System.Text;");
        sb.AppendLine("using global::System.Threading;");
        sb.AppendLine("using global::System.Threading.Tasks;");
        sb.AppendLine("using global::LuminPack.Core;");
        sb.AppendLine("using global::LuminPack.Generated;");
        sb.AppendLine("using global::LuminPack.Option;");
        sb.AppendLine("using global::LuminPack.Utility;");
        sb.AppendLine("using static global::LuminPack.Code.LuminPackMarshal;");
        sb.AppendLine();
        sb.AppendLine("namespace LuminPack");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Provides convenience and reusable-buffer APIs for LuminPack binary and JSON serialization.</summary>");
        sb.AppendLine("    /// <remarks>Convenience overloads accept per-call options. Overloads accepting <see cref=\"LuminBufferWriter\"/> use");
        sb.AppendLine("    /// the option and operation state owned by that writer for a ThreadStatic-free high-performance path.</remarks>");
        sb.AppendLine("    public static class LuminPackSerializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [ThreadStatic]");
        sb.AppendLine("        private static LuminPackWriterOptionalState? _threadStaticWriterOptionalState;");
        sb.AppendLine("        [ThreadStatic]");
        sb.AppendLine("        private static LuminPackReaderOptionalState? _threadStaticReaderOptionalState;");
        sb.AppendLine("        [ThreadStatic]");
        sb.AppendLine("        private static LuminPackEvaluatorOptionState? _threadStaticEvaluatorOptionalState;");
        sb.AppendLine();

        foreach (ITypeSymbol type in orderedTypes)
        {
            string typeName = FormatterTypeName.Get(type);
            _currentAccess = type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
            AppendTypeOverloads(sb, typeName, metaInfo);
        }

        _currentAccess = "public";
        AppendGenericFallbacks(sb, metaInfo);

        AppendCompressDecompress(sb);

        AppendPrivateHelpers(sb);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendTypeOverloads(StringBuilder sb, string typeName, MetaInfo metaInfo)
    {
        AppendSerialize(sb, typeName);
        AppendSerializeBuffer(sb, typeName);
        AppendSerializeJson(sb, typeName);
        AppendSerializeJsonBuffer(sb, typeName);
        AppendSerializeAsync(sb, typeName, metaInfo);
        AppendDeserializeSpanRef(sb, typeName);
        AppendDeserializeBufferRef(sb, typeName);
        AppendDeserializeSequenceRef(sb, typeName);
        AppendDeserializeJsonStringRef(sb, typeName);
        AppendDeserializeJsonSpanByteRef(sb, typeName);
        AppendDeserializeJsonSpanCharRef(sb, typeName);
        AppendDeserializeJsonBufferRef(sb, typeName);
        AppendDeserializeAsyncValue(sb, typeName);
        AppendSizeof(sb, typeName);
    }

    private static void AppendSerialize(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Serializes <paramref name=\"value\"/> to a newly allocated LuminPack binary payload.</summary>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this call, or <see langword=\"null\"/> for LuminPack defaults.</param>");
        sb.AppendLine("        /// <returns>A new byte array containing the complete serialized payload.</returns>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// This convenience overload allocates the returned array and may use thread-static operation state.");
        sb.AppendLine("        /// Use <see cref=\"Serialize(LuminBufferWriter)\"/> (untyped overload) or the buffer overload to reuse a buffer and avoid the");
        sb.AppendLine("        /// serializer's thread-static optional-state path.");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static byte[] Serialize(in " + typeName + " value, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var writerBuffer = LuminBufferWriterPool.Rent();");
        sb.AppendLine();
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackWriter(writerBuffer, state);");
        sb.AppendLine();
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine();
        sb.AppendLine("                var buffer = AllocateUninitializedArray<byte>(writer.CurrentIndex);");
        sb.AppendLine("                writer.GetSpan().CopyTo(buffer.AsSpan());");
        sb.AppendLine("                return buffer;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                LuminBufferWriterPool.Return(writerBuffer);");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendSerializeBuffer(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Serializes <paramref name=\"value\"/> into a reusable <see cref=\"LuminBufferWriter\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"writerBuffer\">The exclusive buffer and operation context that receives the payload.</param>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// <para>This high-performance overload obtains its configuration from <see cref=\"LuminBufferWriter.Option\"/>.</para>");
        sb.AppendLine("        /// <para>Configure <paramref name=\"writerBuffer\"/> before this call. Its option remains unchanged for the current");
        sb.AppendLine("        /// Rent-to-Return lifetime and is restored to defaults by <see cref=\"LuminBufferWriterPool.Return\"/>.</para>");
        sb.AppendLine("        /// <para>The method uses the writer state owned by <paramref name=\"writerBuffer\"/> and does not access the");
        sb.AppendLine("        /// serializer's thread-static optional state. The caller must exclusively own the buffer until it is returned.</para>");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static void Serialize(in " + typeName + " value, LuminBufferWriter writerBuffer)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = writerBuffer.WriterState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackWriter(writerBuffer, state);");
        sb.AppendLine();
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine();
        sb.AppendLine("                writerBuffer.CompleteWrite(writer.CurrentIndex);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch");
        sb.AppendLine("            {");
        sb.AppendLine("                writerBuffer.ResetCore();");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendSerializeJson(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Serializes <paramref name=\"value\"/> to a newly allocated JSON string.</summary>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this call, or <see langword=\"null\"/> for LuminPack defaults.</param>");
        sb.AppendLine("        /// <returns>A new string containing the complete JSON document.</returns>");
        sb.AppendLine("        /// <remarks>This convenience overload allocates the returned string and may use thread-static operation state.</remarks>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static string SerializeJson(" + typeName + " value, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var writerBuffer = LuminBufferWriterPool.Rent();");
        sb.AppendLine();
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine();
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackJsonWriter(writerBuffer, state);");
        sb.AppendLine();
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine();
        sb.AppendLine("                return writer.Option.StringEncoding is LuminPackStringEncoding.UTF8");
        sb.AppendLine("                    ? Encoding.UTF8.GetString(writer.GetSpan())");
        sb.AppendLine("                    : Encoding.Unicode.GetString(writer.GetSpan());");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("                LuminBufferWriterPool.Return(writerBuffer);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendSerializeJsonBuffer(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Serializes <paramref name=\"value\"/> as JSON into a reusable <see cref=\"LuminBufferWriter\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"writerBuffer\">The exclusive buffer and operation context that receives the JSON bytes.</param>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// <para>The JSON encoding and other settings come from <see cref=\"LuminBufferWriter.Option\"/>; this overload");
        sb.AppendLine("        /// intentionally has no separate option parameter.</para>");
        sb.AppendLine("        /// <para>The option remains configured throughout the current Rent-to-Return lifetime and is restored to defaults");
        sb.AppendLine("        /// by <see cref=\"LuminBufferWriterPool.Return\"/>. Writer and reader temporary state are cleared as part of Return.</para>");
        sb.AppendLine("        /// <para>This high-performance path does not access serializer thread-static optional state. Do not use the same");
        sb.AppendLine("        /// buffer concurrently or reenter this method with that buffer.</para>");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static void SerializeJson(" + typeName + " value, LuminBufferWriter writerBuffer)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = writerBuffer.WriterState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackJsonWriter(writerBuffer, state);");
        sb.AppendLine();
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine();
        sb.AppendLine("                writerBuffer.CompleteWrite(writer.CurrentIndex);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch");
        sb.AppendLine("            {");
        sb.AppendLine("                writerBuffer.ResetCore();");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendSerializeAsync(StringBuilder sb, string typeName, MetaInfo metaInfo)
    {
        sb.AppendLine("        /// <summary>Asynchronously serializes <paramref name=\"value\"/> and writes the binary payload to a stream.</summary>");
        sb.AppendLine("        /// <param name=\"stream\">The destination stream.</param>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this operation, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <param name=\"cancellationToken\">A token that can cancel stream writes and flushing.</param>");
        sb.AppendLine("        /// <returns>A task-like value that completes after the stream has been flushed.</returns>");
        sb.AppendLine("        /// <remarks>This convenience API internally rents and returns a buffer; the caller does not manage that buffer.</remarks>");
        sb.AppendLine("        " + _currentAccess + " static async ValueTask SerializeAsync(");
        sb.AppendLine("            Stream stream, " + typeName + " value,");
        sb.AppendLine("            LuminPackSerializerOption? option = null,");
        sb.AppendLine("            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            var tempWriter = LuminBufferWriterPool.Rent();");
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        if (metaInfo.IsNet9_OR_GREATER)
        {
            // For .NET 9+ keep the original code directly (compiler allows it)
            sb.AppendLine("                var writer = new LuminPackWriter(tempWriter, state);");
            sb.AppendLine("                writer.WriteValue(in value);");
            sb.AppendLine("                tempWriter.CompleteWrite(writer.CurrentIndex);");
        }
        else
        {
            // For older frameworks, define a static local function that does the synchronous serialization
            sb.AppendLine("                static void WriteValue(LuminBufferWriter tempWriter, LuminPackWriterOptionalState state, in " + typeName + " value)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var writer = new LuminPackWriter(tempWriter, state);");
            sb.AppendLine("                    writer.WriteValue(in value);");
            sb.AppendLine("                    tempWriter.CompleteWrite(writer.CurrentIndex);");
            sb.AppendLine("                }");
            sb.AppendLine("                WriteValue(tempWriter, state, in value);");
        }

        sb.AppendLine("                await tempWriter.WriteToAndResetAsync(stream, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("                await stream.FlushAsync(cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("                LuminBufferWriterPool.Return(tempWriter);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeSpanRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes a binary span into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"buffer\">The span containing a complete or leading LuminPack payload.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of bytes consumed.</returns>");
        sb.AppendLine("        /// <remarks>This convenience overload may use thread-static reader operation state.</remarks>");
        sb.AppendLine("        " + _currentAccess + " static int Deserialize(");
        sb.AppendLine("            ReadOnlySpan<byte> buffer, ref " + typeName + " value,");
        sb.AppendLine("            LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine();
        sb.AppendLine("            var reader = new LuminPackReader(ref buffer, state);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return reader.GetCurrentSpanIndex();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeBufferRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes into <paramref name=\"value\"/> from a reusable <see cref=\"LuminBufferWriter\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The buffer containing binary data and the reader operation context.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <returns>The number of bytes consumed from the buffer.</returns>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// Configuration comes from <see cref=\"LuminBufferWriter.Option\"/> and persists until the buffer is returned.");
        sb.AppendLine("        /// <see cref=\"LuminBufferWriterPool.Return\"/> restores defaults and clears both operation states. This method does");
        sb.AppendLine("        /// not use thread-static optional state and requires exclusive ownership of <paramref name=\"bufferWriter\"/>.");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        " + _currentAccess + " static int Deserialize(LuminBufferWriter bufferWriter, ref " + typeName + " value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = bufferWriter.ReaderState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var bytes = bufferWriter.GetSpan();");
        sb.AppendLine("                var reader = new LuminPackReader(ref bytes, state);");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return reader.GetCurrentSpanIndex();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeSequenceRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes a possibly multi-segment sequence into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"buffer\">The sequence containing a LuminPack payload.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of bytes consumed.</returns>");
        sb.AppendLine("        /// <remarks>This convenience overload may use thread-static reader operation state.</remarks>");
        sb.AppendLine("        " + _currentAccess + " static int Deserialize(");
        sb.AppendLine("            ReadOnlySequence<byte> buffer, ref " + typeName + " value,");
        sb.AppendLine("            LuminPackSerializerOption? options = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!RuntimeHelpers.IsReferenceOrContainsReferences<" + typeName + ">())");
        sb.AppendLine("            {");
        sb.AppendLine("                return DeserializeUnmanagedSequence(buffer, ref value);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine();
        sb.AppendLine("            var reader = new LuminPackReader(ref buffer, state);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return reader.GetCurrentSpanIndex();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeJsonStringRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes JSON from <paramref name=\"buffer\"/> into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"buffer\">The JSON document.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of consumed characters/bytes.</returns>");
        sb.AppendLine("        /// <remarks>This overload performs any required text transcoding and may use pooled temporary storage.</remarks>");
        sb.AppendLine("        " + _currentAccess + " static int DeserializeJson(string buffer, ref " + typeName + " value, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (buffer is null) global::LuminPack.Code.LuminPackExceptionHelper.ThrowArgumentNullException(nameof(buffer));");
        sb.AppendLine("            if (options == null || options.StringEncoding is LuminPackStringEncoding.UTF8)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (buffer.Length > 1024)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var byteCount = Encoding.UTF8.GetByteCount(buffer);");
        sb.AppendLine("                    byte[] byteBuffer = ArrayPool<byte>.Shared.Rent(byteCount);");
        sb.AppendLine("                    try");
        sb.AppendLine("                    {");
        sb.AppendLine("                        Encoding.UTF8.GetBytes(buffer, 0, buffer.Length, byteBuffer, 0);");
        sb.AppendLine("                        return DeserializeJson(byteBuffer.AsSpan(0, byteCount), ref value, options);");
        sb.AppendLine("                    }");
        sb.AppendLine("                    finally");
        sb.AppendLine("                    {");
        sb.AppendLine("                        ArrayPool<byte>.Shared.Return(byteBuffer);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine("                    Span<byte> span = stackalloc byte[buffer.Length * 3];");
        sb.AppendLine("                    var written = Encoding.UTF8.GetBytes(buffer, span);");
        sb.AppendLine("                    return DeserializeJson(span[..written], ref value, options);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                return DeserializeJson(buffer.AsSpan(), ref value, options);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeJsonSpanByteRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes JSON from <paramref name=\"buffer\"/> into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"buffer\">The JSON byte span.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of consumed bytes.</returns>");
        sb.AppendLine("        " + _currentAccess + " static int DeserializeJson(ReadOnlySpan<byte> buffer, ref " + typeName + " value, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = new LuminPackJsonReader(ref buffer, state);");
        sb.AppendLine("                if (!reader.Read()) global::LuminPack.Code.LuminPackExceptionHelper.ThrowFormatException(\"JSON input does not contain a value\");");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                reader.EnsureEndOfDocument();");
        sb.AppendLine("                return reader.CurrentIndex;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeJsonSpanCharRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes JSON from <paramref name=\"buffer\"/> into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"buffer\">The JSON character span.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of consumed characters.</returns>");
        sb.AppendLine("        /// <remarks>This overload may use thread-static reader operation state.</remarks>");
        sb.AppendLine("        " + _currentAccess + " static int DeserializeJson(ReadOnlySpan<char> buffer, ref " + typeName + " value, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (options?.StringEncoding is not LuminPackStringEncoding.UTF16)");
        sb.AppendLine("            {");
        sb.AppendLine("                int byteCount = Encoding.UTF8.GetByteCount(buffer);");
        sb.AppendLine("                byte[] rented = ArrayPool<byte>.Shared.Rent(byteCount);");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    int written = Encoding.UTF8.GetBytes(buffer, rented);");
        sb.AppendLine("                    return DeserializeJson(rented.AsSpan(0, written), ref value, options);");
        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        sb.AppendLine("                    ArrayPool<byte>.Shared.Return(rented);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var span = MemoryMarshal.Cast<char, byte>(buffer);");
        sb.AppendLine("                var reader = new LuminPackJsonReader(ref span, state);");
        sb.AppendLine("                if (!reader.Read()) global::LuminPack.Code.LuminPackExceptionHelper.ThrowFormatException(\"JSON input does not contain a value\");");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                reader.EnsureEndOfDocument();");
        sb.AppendLine("                return reader.CurrentIndex;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeJsonBufferRef(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Deserializes JSON from a reusable <see cref=\"LuminBufferWriter\"/> into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The buffer containing JSON bytes and the reader operation context.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <returns>The number of consumed bytes.</returns>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// <para>JSON encoding and all other settings come from <see cref=\"LuminBufferWriter.Option\"/>. The option remains");
        sb.AppendLine("        /// configured for the current Rent-to-Return lifetime and is reset by <see cref=\"LuminBufferWriterPool.Return\"/>.</para>");
        sb.AppendLine("        /// <para>This high-performance overload uses the buffer-owned reader state and never accesses serializer");
        sb.AppendLine("        /// thread-static optional state. The buffer must be exclusively owned and cannot be used for same-instance reentry.</para>");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine("        " + _currentAccess + " static int DeserializeJson(LuminBufferWriter bufferWriter, ref " + typeName + " value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = bufferWriter.ReaderState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var bytes = bufferWriter.GetSpan();");
        sb.AppendLine("                var reader = new LuminPackJsonReader(ref bytes, state);");
        sb.AppendLine("                if (!reader.Read()) global::LuminPack.Code.LuminPackExceptionHelper.ThrowFormatException(\"JSON input does not contain a value\");");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                reader.EnsureEndOfDocument();");
        sb.AppendLine("                return reader.CurrentIndex;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDeserializeAsyncValue(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Asynchronously reads a stream and deserializes into an existing or default <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <param name=\"stream\">The source stream.</param>");
        sb.AppendLine("        /// <param name=\"value\">The initial value supplied to parsers that can reuse instances.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this operation, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <param name=\"cancellationToken\">A token that can cancel stream reads.</param>");
        sb.AppendLine("        /// <returns>A task-like value containing the deserialized value.</returns>");
        sb.AppendLine("        /// <remarks>This convenience API manages its own pooled read buffers; no BufferWriter must be returned by the caller.</remarks>");
        sb.AppendLine("        " + _currentAccess + " static async ValueTask<" + typeName + "> DeserializeAsync(");
        sb.AppendLine("            Stream stream, " + typeName + " value, LuminPackSerializerOption? options = null,");
        sb.AppendLine("            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            using var data = new MemoryStream();");
        sb.AppendLine("            await stream.CopyToAsync(data, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return Deserialize<" + typeName + ">(data.GetBuffer().AsSpan(0, checked((int)data.Length)), options);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendSizeof(StringBuilder sb, string typeName)
    {
        sb.AppendLine("        /// <summary>Calculates the binary payload size for <paramref name=\"value\"/> without producing the payload.</summary>");
        sb.AppendLine("        /// <param name=\"value\">The value whose serialized size is calculated.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this calculation, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of bytes required by binary serialization.</returns>");
        sb.AppendLine("        /// <remarks>This convenience API may use thread-static evaluator state and does not modify a BufferWriter.</remarks>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static int Sizeof(" + typeName + " value, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticEvaluatorOptionalState ??= new LuminPackEvaluatorOptionState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var totalLength = 0;");
        sb.AppendLine();
        sb.AppendLine("                var evaluator = new LuminPackEvaluator(ref totalLength, state);");
        sb.AppendLine();
        sb.AppendLine("                evaluator.CalculateOffset(ref value);");
        sb.AppendLine();
        sb.AppendLine("                return totalLength;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericFallbacks(StringBuilder sb, MetaInfo metaInfo)
    {
        AppendGenericSerialize(sb);
        AppendGenericSerializeBufferWriter(sb);
        AppendGenericSerializeJson(sb);
        AppendGenericSerializeJsonBufferWriter(sb);
        AppendGenericSizeof(sb);
        AppendGenericDeserializeSpan(sb);
        AppendGenericDeserializeSpanRef(sb);
        AppendGenericDeserializeBuffer(sb);
        AppendGenericDeserializeBufferRef(sb);
        AppendGenericDeserializeSequence(sb);
        AppendGenericDeserializeSequenceRef(sb);
        AppendGenericDeserializeJsonString(sb);
        AppendGenericDeserializeJsonSpanByte(sb);
        AppendGenericDeserializeJsonSpanChar(sb);
        AppendGenericDeserializeJsonBuffer(sb);
        AppendGenericDeserializeAsync(sb);
        AppendGenericDeserializeAsyncValue(sb);
    }

    private static void AppendGenericSerialize(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Serializes a <typeparamref name=\"T\"/> to a newly allocated LuminPack binary payload using the generated generic dispatch.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The value type to serialize.</typeparam>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this call, or <see langword=\"null\"/> for LuminPack defaults.</param>");
        sb.AppendLine("        /// <returns>A new byte array containing the complete serialized payload.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static byte[] Serialize<T>(in T value, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var writerBuffer = LuminBufferWriterPool.Rent();");
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackWriter(writerBuffer, state);");
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine("                var buffer = AllocateUninitializedArray<byte>(writer.CurrentIndex);");
        sb.AppendLine("                writer.GetSpan().CopyTo(buffer.AsSpan());");
        sb.AppendLine("                return buffer;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                LuminBufferWriterPool.Return(writerBuffer);");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits a generic <c>Serialize&lt;T&gt;(in T, IBufferWriter&lt;byte&gt;)</c> overload.  Serialization
    /// runs through the existing LuminBufferWriter fast path (native buffer, concrete method calls only)
    /// and the published payload is copied into the caller's <c>IBufferWriter&lt;byte&gt;</c> (e.g. a
    /// <c>System.IO.Pipelines.PipeWriter</c> or <c>ArrayBufferWriter&lt;byte&gt;</c>).  The internal
    /// generated call path is untouched, so no interface virtual dispatch enters the hot path.
    /// </summary>
    private static void AppendGenericSerializeBufferWriter(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Serializes a <typeparamref name=\"T\"/> into an arbitrary <see cref=\"IBufferWriter{T}\"/> using the generated generic dispatch.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The value type to serialize.</typeparam>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The destination writer, e.g. <c>System.IO.Pipelines.PipeWriter</c> or <c>ArrayBufferWriter&lt;byte&gt;</c>.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this call, or <see langword=\"null\"/> for LuminPack defaults.</param>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static void Serialize<T>(in T value, global::System.Buffers.IBufferWriter<byte> bufferWriter, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (bufferWriter is null) global::LuminPack.Code.LuminPackExceptionHelper.ThrowArgumentNullException(nameof(bufferWriter));");
        sb.AppendLine("            var writerBuffer = LuminBufferWriterPool.Rent();");
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackWriter(writerBuffer, state);");
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine("                var source = writer.GetSpan();");
        sb.AppendLine("                var dest = bufferWriter.GetSpan(source.Length);");
        sb.AppendLine("                source.CopyTo(dest);");
        sb.AppendLine("                bufferWriter.Advance(source.Length);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                LuminBufferWriterPool.Return(writerBuffer);");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits a generic <c>SerializeJson&lt;T&gt;(T, IBufferWriter&lt;byte&gt;)</c> overload writing the JSON
    /// bytes (in the configured encoding) into an arbitrary <c>IBufferWriter&lt;byte&gt;</c>.
    /// </summary>
    private static void AppendGenericSerializeJsonBufferWriter(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Serializes <typeparamref name=\"T\"/> as JSON bytes into an arbitrary <see cref=\"IBufferWriter{T}\"/> using the generated generic dispatch.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The value type to serialize.</typeparam>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The destination writer that receives the JSON bytes.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this call, or <see langword=\"null\"/> for LuminPack defaults.</param>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static void SerializeJson<T>(T value, global::System.Buffers.IBufferWriter<byte> bufferWriter, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (bufferWriter is null) global::LuminPack.Code.LuminPackExceptionHelper.ThrowArgumentNullException(nameof(bufferWriter));");
        sb.AppendLine("            var writerBuffer = LuminBufferWriterPool.Rent();");
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackJsonWriter(writerBuffer, state);");
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine("                var source = writer.GetSpan();");
        sb.AppendLine("                var dest = bufferWriter.GetSpan(source.Length);");
        sb.AppendLine("                source.CopyTo(dest);");
        sb.AppendLine("                bufferWriter.Advance(source.Length);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                LuminBufferWriterPool.Return(writerBuffer);");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericSerializeJson(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Serializes a <typeparamref name=\"T\"/> to a newly allocated JSON string using the generated generic dispatch.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The value type to serialize.</typeparam>");
        sb.AppendLine("        /// <param name=\"value\">The value to serialize.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this call, or <see langword=\"null\"/> for LuminPack defaults.</param>");
        sb.AppendLine("        /// <returns>A new string containing the complete JSON document.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static string SerializeJson<T>(T value, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var writerBuffer = LuminBufferWriterPool.Rent();");
        sb.AppendLine("            var state = _threadStaticWriterOptionalState ??= new LuminPackWriterOptionalState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var writer = new LuminPackJsonWriter(writerBuffer, state);");
        sb.AppendLine("                writer.WriteValue(in value);");
        sb.AppendLine("                return writer.Option.StringEncoding is LuminPackStringEncoding.UTF8");
        sb.AppendLine("                    ? Encoding.UTF8.GetString(writer.GetSpan())");
        sb.AppendLine("                    : Encoding.Unicode.GetString(writer.GetSpan());");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("                LuminBufferWriterPool.Return(writerBuffer);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericSizeof(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Calculates the binary payload size for a <typeparamref name=\"T\"/> without producing the payload.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The value type to evaluate.</typeparam>");
        sb.AppendLine("        /// <param name=\"value\">The value whose serialized size is calculated.</param>");
        sb.AppendLine("        /// <param name=\"option\">The configuration for this calculation, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of bytes required by binary serialization.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static int Sizeof<T>(T value, LuminPackSerializerOption? option = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticEvaluatorOptionalState ??= new LuminPackEvaluatorOptionState();");
        sb.AppendLine("            state.Init(option);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var totalLength = 0;");
        sb.AppendLine("                var evaluator = new LuminPackEvaluator(ref totalLength, state);");
        sb.AppendLine("                evaluator.CalculateOffset(ref value);");
        sb.AppendLine("                return totalLength;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeSpan(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from a binary span using the generated generic dispatch.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The span containing a complete or leading LuminPack payload.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        /// <remarks>This convenience overload may use thread-static reader operation state.</remarks>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static T Deserialize<T>(ReadOnlySpan<byte> buffer, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine();
        sb.AppendLine("            var reader = new LuminPackReader(ref buffer, state);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                T value = default!;");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return value;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeSpanRef(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a binary span into <paramref name=\"value\"/> using the generated generic dispatch.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The span containing a complete or leading LuminPack payload.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of bytes consumed.</returns>");
        sb.AppendLine("        " + _currentAccess + " static int Deserialize<T>(");
        sb.AppendLine("            ReadOnlySpan<byte> buffer, ref T value,");
        sb.AppendLine("            LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine();
        sb.AppendLine("            var reader = new LuminPackReader(ref buffer, state);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return reader.GetCurrentSpanIndex();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeBuffer(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from a reusable <see cref=\"LuminBufferWriter\"/>.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The buffer containing binary data and the reader operation context.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static T Deserialize<T>(LuminBufferWriter bufferWriter)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = bufferWriter.ReaderState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                T value = default!;");
        sb.AppendLine("                var bytes = bufferWriter.GetSpan();");
        sb.AppendLine("                var reader = new LuminPackReader(ref bytes, state);");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return value;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeBufferRef(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes into <paramref name=\"value\"/> from a reusable <see cref=\"LuminBufferWriter\"/>.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The buffer containing binary data and the reader operation context.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <returns>The number of bytes consumed from the buffer.</returns>");
        sb.AppendLine("        " + _currentAccess + " static int Deserialize<T>(LuminBufferWriter bufferWriter, ref T value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = bufferWriter.ReaderState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var bytes = bufferWriter.GetSpan();");
        sb.AppendLine("                var reader = new LuminPackReader(ref bytes, state);");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return reader.GetCurrentSpanIndex();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeSequence(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from a possibly multi-segment sequence.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The sequence containing a LuminPack payload.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static T Deserialize<T>(in ReadOnlySequence<byte> buffer, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            T value = default!;");
        sb.AppendLine("            Deserialize(buffer, ref value, options);");
        sb.AppendLine("            return value;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeSequenceRef(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a possibly multi-segment sequence into <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The sequence containing a LuminPack payload.</param>");
        sb.AppendLine("        /// <param name=\"value\">Receives the deserialized value.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The number of bytes consumed.</returns>");
        sb.AppendLine("        " + _currentAccess + " static int Deserialize<T>(");
        sb.AppendLine("            ReadOnlySequence<byte> buffer, ref T value,");
        sb.AppendLine("            LuminPackSerializerOption? options = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine();
        sb.AppendLine("            var reader = new LuminPackReader(ref buffer, state);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                return reader.GetCurrentSpanIndex();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeJsonString(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from a JSON string.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The JSON document.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static T DeserializeJson<T>(string buffer, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (buffer is null) global::LuminPack.Code.LuminPackExceptionHelper.ThrowArgumentNullException(nameof(buffer));");
        sb.AppendLine("            return DeserializeJson<T>(buffer.AsSpan(), options);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeJsonSpanByte(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from a JSON byte span.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The JSON byte span.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        " + _currentAccess + " static T DeserializeJson<T>(ReadOnlySpan<byte> buffer, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            T value = default!;");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = new LuminPackJsonReader(ref buffer, state);");
        sb.AppendLine("                if (!reader.Read()) global::LuminPack.Code.LuminPackExceptionHelper.ThrowFormatException(\"JSON input does not contain a value\");");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                reader.EnsureEndOfDocument();");
        sb.AppendLine("                return value;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeJsonSpanChar(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from a UTF-16 JSON character span.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"buffer\">The JSON character span.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this call, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static T DeserializeJson<T>(ReadOnlySpan<char> buffer, LuminPackSerializerOption? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (options?.StringEncoding is not LuminPackStringEncoding.UTF16)");
        sb.AppendLine("            {");
        sb.AppendLine("                int byteCount = Encoding.UTF8.GetByteCount(buffer);");
        sb.AppendLine("                byte[] rented = ArrayPool<byte>.Shared.Rent(byteCount);");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    int written = Encoding.UTF8.GetBytes(buffer, rented);");
        sb.AppendLine("                    return DeserializeJson<T>(rented.AsSpan(0, written), options);");
        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        sb.AppendLine("                    ArrayPool<byte>.Shared.Return(rented);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            T value = default!;");
        sb.AppendLine("            var state = _threadStaticReaderOptionalState ??= new LuminPackReaderOptionalState();");
        sb.AppendLine("            state.Init(options);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var bytes = MemoryMarshal.Cast<char, byte>(buffer);");
        sb.AppendLine("                var reader = new LuminPackJsonReader(ref bytes, state);");
        sb.AppendLine("                if (!reader.Read()) global::LuminPack.Code.LuminPackExceptionHelper.ThrowFormatException(\"JSON input does not contain a value\");");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                reader.EnsureEndOfDocument();");
        sb.AppendLine("                return value;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.Reset();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeJsonBuffer(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Deserializes a <typeparamref name=\"T\"/> from JSON bytes in a reusable <see cref=\"LuminBufferWriter\"/>.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"bufferWriter\">The buffer containing JSON bytes and the reader operation context.</param>");
        sb.AppendLine("        /// <returns>The deserialized value.</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static T DeserializeJson<T>(LuminBufferWriter bufferWriter)");
        sb.AppendLine("        {");
        sb.AppendLine("            T value = default!;");
        sb.AppendLine("            var state = bufferWriter.ReaderState;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var bytes = bufferWriter.GetSpan();");
        sb.AppendLine("                var reader = new LuminPackJsonReader(ref bytes, state);");
        sb.AppendLine("                if (!reader.Read()) global::LuminPack.Code.LuminPackExceptionHelper.ThrowFormatException(\"JSON input does not contain a value\");");
        sb.AppendLine("                reader.ReadValue(ref value);");
        sb.AppendLine("                reader.EnsureEndOfDocument();");
        sb.AppendLine("                return value;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                state.ResetOperationState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeAsync(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Asynchronously reads a stream to completion and deserializes one <typeparamref name=\"T\"/>.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"stream\">The source stream.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this operation, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <param name=\"cancellationToken\">A token that can cancel stream reads.</param>");
        sb.AppendLine("        /// <returns>A task-like value containing the deserialized value.</returns>");
        sb.AppendLine("        " + _currentAccess + " static async ValueTask<T> DeserializeAsync<T>(");
        sb.AppendLine("            Stream stream, LuminPackSerializerOption? options = null,");
        sb.AppendLine("            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            using var data = new MemoryStream();");
        sb.AppendLine("            await stream.CopyToAsync(data, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return Deserialize<T>(data.GetBuffer().AsSpan(0, checked((int)data.Length)), options);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendGenericDeserializeAsyncValue(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Asynchronously reads a stream and deserializes into an existing or default <paramref name=\"value\"/>.</summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">The target value type.</typeparam>");
        sb.AppendLine("        /// <param name=\"stream\">The source stream.</param>");
        sb.AppendLine("        /// <param name=\"value\">The initial value supplied to parsers that can reuse instances.</param>");
        sb.AppendLine("        /// <param name=\"options\">The configuration for this operation, or <see langword=\"null\"/> for defaults.</param>");
        sb.AppendLine("        /// <param name=\"cancellationToken\">A token that can cancel stream reads.</param>");
        sb.AppendLine("        /// <returns>A task-like value containing the deserialized value.</returns>");
        sb.AppendLine("        " + _currentAccess + " static async ValueTask<T> DeserializeAsync<T>(");
        sb.AppendLine("            Stream stream, T value, LuminPackSerializerOption? options = null,");
        sb.AppendLine("            CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            using var data = new MemoryStream();");
        sb.AppendLine("            await stream.CopyToAsync(data, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("            return Deserialize<T>(data.GetBuffer().AsSpan(0, checked((int)data.Length)), options);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendCompressDecompress(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 压缩数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"source\">数据源</param>");
        sb.AppendLine("        /// <param name=\"destination\">目标位置</param>");
        sb.AppendLine("        /// <returns>压缩后长度</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static int Compress(LuminBufferWriter source, LuminBufferWriter destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            return LuminCompressor.Compress(source, destination);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 压缩数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"source\">数据源</param>");
        sb.AppendLine("        /// <returns>压缩后长度</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static byte[] Compress(ReadOnlySpan<byte> source)");
        sb.AppendLine("        {");
        sb.AppendLine("            return LuminCompressor.Compress(source);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 压缩数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"source\">数据源</param>");
        sb.AppendLine("        /// <param name=\"destination\">目标位置</param>");
        sb.AppendLine("        /// <returns>压缩后长度</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static int Compress(ReadOnlySpan<byte> source, Span<byte> destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            return LuminCompressor.Compress(source, destination);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 解压缩数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"source\">数据源</param>");
        sb.AppendLine("        /// <param name=\"destination\">目标位置</param>");
        sb.AppendLine("        /// <returns>解压后长度</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static int Decompress(ReadOnlySpan<byte> source, Span<byte> destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            return LuminCompressor.Decompress(source, destination);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 解压缩数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"source\">数据源</param>");
        sb.AppendLine("        /// <param name=\"destination\">目标位置</param>");
        sb.AppendLine("        /// <returns>解压后长度</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static int Decompress(LuminBufferWriter source, LuminBufferWriter destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            return LuminCompressor.Decompress(source, destination);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 解压缩数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"source\">数据源</param>");
        sb.AppendLine("        /// <returns>解压后长度</returns>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        " + _currentAccess + " static byte[] Decompress(ReadOnlySpan<byte> source)");
        sb.AppendLine("        {");
        sb.AppendLine("            return LuminCompressor.Decompress(source);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendPrivateHelpers(StringBuilder sb)
    {
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        private static int DeserializeUnmanagedSequence<T>(ReadOnlySequence<byte> buffer, ref T value)");
        sb.AppendLine("        {");
        sb.AppendLine("            int size = Unsafe.SizeOf<T>();");
        sb.AppendLine("            if (buffer.Length < size)");
        sb.AppendLine("            {");
        sb.AppendLine("                global::LuminPack.Code.LuminPackExceptionHelper.ThrowInvalidRange(size, (int)buffer.Length);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (buffer.IsSingleSegment)");
        sb.AppendLine("            {");
        sb.AppendLine("                value = Unsafe.ReadUnaligned<T>(ref MemoryMarshal.GetReference(buffer.FirstSpan));");
        sb.AppendLine("                return size;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (size <= 512)");
        sb.AppendLine("            {");
        sb.AppendLine("                Span<byte> tempSpan = stackalloc byte[size];");
        sb.AppendLine("                buffer.Slice(0, size).CopyTo(tempSpan);");
        sb.AppendLine("                value = Unsafe.ReadUnaligned<T>(ref MemoryMarshal.GetReference(tempSpan));");
        sb.AppendLine("                return size;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var rentedBuffer = ArrayPool<byte>.Shared.Rent(size);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var tempSpan = rentedBuffer.AsSpan(0, size);");
        sb.AppendLine("                buffer.Slice(0, size).CopyTo(tempSpan);");
        sb.AppendLine("                value = Unsafe.ReadUnaligned<T>(ref MemoryMarshal.GetReference(tempSpan));");
        sb.AppendLine("                return size;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                ArrayPool<byte>.Shared.Return(rentedBuffer);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
}