using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using LuminPack.SourceGenerator;

namespace LuminPack.Code.Core;

internal static class LuminPackUnionDispatchCodeGenerator
{
    public static string Generate(LuminDataInfo data, Compilation compilation)
    {
        if (!data.isUnion || !data.CanGenerateUnionDispatch || data.TypeSymbol == null)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var root = data.TypeSymbol.OriginalDefinition;
        var suffix = GetSlotSuffix(root);
        var extensionType = "global::LuminPack.Generated.LuminPackExtensions_" +
            SanitizeAssemblyName(compilation.AssemblyName ?? "Assembly");
        AppendPartialType(sb, root, (builder, indent) =>
            AppendRootMethods(builder, indent, root, suffix));

        foreach (var group in data.UnionMembers
                     .Where(member => IsFastPathMember(data, member))
                     .GroupBy(member => member.Type.OriginalDefinition, SymbolEqualityComparer.Default))
        {
            var members = group.ToList();
            var definition = members[0].Type.OriginalDefinition;
            var matchedRoot = FindMatchedRoot(definition, root);
            if (matchedRoot == null)
                continue;

            var canSeal = root.TypeKind == TypeKind.Class && !HasDerivedUnionMember(data, definition);

            AppendPartialType(sb, definition, (builder, indent) =>
                AppendMemberMethods(builder, indent, data, root, matchedRoot, members, suffix, extensionType, canSeal));
        }

        return sb.ToString();
    }

    internal static bool IsFastPathMember(LuminDataInfo data, LuminUnionMemberInfo member)
    {
        if (!data.CanGenerateUnionDispatch || !member.CanGenerateDispatch)
            return false;

        return FindMatchedRoot(member.Type.OriginalDefinition, data.TypeSymbol.OriginalDefinition) != null;
    }

    private static void AppendRootMethods(
        StringBuilder sb,
        int indent,
        INamedTypeSymbol root,
        string suffix)
    {
        var padding = new string(' ', indent * 4);
        var rootType = root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var modifier = root.TypeKind == TypeKind.Interface ? string.Empty : "internal virtual ";

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{modifier}void __LuminPackUnionSerialize_{suffix}(ref global::LuminPack.Core.LuminPackWriter writer)");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(((object)this).GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{modifier}void __LuminPackUnionSerializeJson_{suffix}(ref global::LuminPack.Core.LuminPackJsonWriter writer)");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(((object)this).GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{modifier}void __LuminPackUnionCalculateOffset_{suffix}(ref global::LuminPack.Core.LuminPackEvaluator evaluator)");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(((object)this).GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}}}");
    }

    private static void AppendMemberMethods(
        StringBuilder sb,
        int indent,
        LuminDataInfo data,
        INamedTypeSymbol root,
        INamedTypeSymbol matchedRoot,
        IReadOnlyList<LuminUnionMemberInfo> members,
        string suffix,
        string extensionType,
        bool canSeal)
    {
        var padding = new string(' ', indent * 4);
        var bodyPadding = new string(' ', (indent + 1) * 4);
        var rootType = matchedRoot.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var isInterface = root.TypeKind == TypeKind.Interface;
        var prefix = isInterface
            ? $"void {rootType}."
            : (canSeal ? "internal sealed override void " : "internal override void ");

        if (RequiresClosedGenericDispatch(members))
        {
            AppendClosedGenericDispatchCache(sb, padding, data, members, suffix);
            sb.AppendLine();
        }

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{prefix}__LuminPackUnionSerialize_{suffix}(ref global::LuminPack.Core.LuminPackWriter writer)");
        sb.AppendLine($"{padding}{{");
        AppendMemberDispatchBody(sb, bodyPadding, data, members, rootType, DispatchOperation.Binary, extensionType);
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{prefix}__LuminPackUnionSerializeJson_{suffix}(ref global::LuminPack.Core.LuminPackJsonWriter writer)");
        sb.AppendLine($"{padding}{{");
        AppendMemberDispatchBody(sb, bodyPadding, data, members, rootType, DispatchOperation.Json, extensionType);
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{prefix}__LuminPackUnionCalculateOffset_{suffix}(ref global::LuminPack.Core.LuminPackEvaluator evaluator)");
        sb.AppendLine($"{padding}{{");
        AppendMemberDispatchBody(sb, bodyPadding, data, members, rootType, DispatchOperation.CalculateOffset, extensionType);
        sb.AppendLine($"{padding}}}");
    }

    private static void AppendMemberDispatchBody(
        StringBuilder sb,
        string padding,
        LuminDataInfo data,
        IReadOnlyList<LuminUnionMemberInfo> members,
        string rootType,
        DispatchOperation operation,
        string extensionType)
    {
        if (!RequiresClosedGenericDispatch(members))
        {
            AppendConcreteOperation(sb, padding, data, members[0], operation, extensionType);
            return;
        }

        var suffix = GetSlotSuffix(data.TypeSymbol.OriginalDefinition);
        sb.AppendLine($"{padding}switch (__LuminPackUnionDispatchSlot_{suffix})");
        sb.AppendLine($"{padding}{{");
        foreach (var member in members)
        {
            sb.AppendLine($"{padding}    case {GetDispatchSlot(data, member)}:");
            sb.AppendLine($"{padding}    {{");
            AppendConcreteOperation(sb, padding + "        ", data, member, operation, extensionType);
            sb.AppendLine($"{padding}        return;");
            sb.AppendLine($"{padding}    }}");
        }
        sb.AppendLine($"{padding}    default:");
        sb.AppendLine($"{padding}        global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}        return;");
        sb.AppendLine($"{padding}}}");
    }

    private static void AppendClosedGenericDispatchCache(
        StringBuilder sb,
        string padding,
        LuminDataInfo data,
        IReadOnlyList<LuminUnionMemberInfo> members,
        string suffix)
    {
        var definition = members[0].Type.OriginalDefinition;
        var currentType = definition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var fieldName = $"__LuminPackUnionDispatchSlot_{suffix}";
        var resolverName = $"__ResolveLuminPackUnionDispatchSlot_{suffix}";

        sb.AppendLine($"{padding}private static readonly int {fieldName} = {resolverName}();");
        sb.AppendLine();
        sb.AppendLine($"{padding}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        sb.AppendLine($"{padding}private static int {resolverName}()");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    var map = new global::LuminPack.Utility.LuminUnionMap<int>({members.Count});");

        // Closed registrations must win over an open-generic fallback when the current
        // instantiation happens to describe the same runtime type.
        foreach (var member in members.Where(member => IsConstructedMember(definition, member)))
        {
            AppendDispatchRegistration(sb, padding + "    ", data, definition, member);
        }

        foreach (var member in members.Where(member => !IsConstructedMember(definition, member)))
        {
            AppendDispatchRegistration(sb, padding + "    ", data, definition, member);
        }

        sb.AppendLine($"{padding}    var methodTable = global::LuminPack.Code.LuminPackMarshal.GetMethodTable(typeof({currentType}));");
        sb.AppendLine($"{padding}    return map.TryGetValue(methodTable, out var slot) ? slot : -1;");
        sb.AppendLine($"{padding}}}");
    }

    private static void AppendDispatchRegistration(
        StringBuilder sb,
        string padding,
        LuminDataInfo data,
        INamedTypeSymbol definition,
        LuminUnionMemberInfo member)
    {
        // The resolver is emitted inside the member definition, so an open fallback
        // must use that definition's in-scope type parameters (which need not have the
        // same names as the union root's parameters).
        var memberType = IsConstructedMember(definition, member)
            ? member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : definition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.AppendLine($"{padding}map.TryRegister(" +
            $"global::LuminPack.Code.LuminPackMarshal.GetMethodTable(typeof({memberType})), " +
            $"{GetDispatchSlot(data, member)});");
    }

    private static bool RequiresClosedGenericDispatch(IReadOnlyList<LuminUnionMemberInfo> members)
    {
        var definition = members[0].Type.OriginalDefinition;
        return members.Any(member => IsConstructedMember(definition, member));
    }

    private static bool IsConstructedMember(INamedTypeSymbol definition, LuminUnionMemberInfo member) =>
        !SymbolEqualityComparer.Default.Equals(member.Type, definition) && !member.Type.IsUnboundGenericType;

    private static int GetDispatchSlot(LuminDataInfo data, LuminUnionMemberInfo member)
    {
        for (var index = 0; index < data.UnionMembers.Count; index++)
        {
            var candidate = data.UnionMembers[index];
            if (candidate.Id == member.Id &&
                SymbolEqualityComparer.Default.Equals(candidate.Type, member.Type))
            {
                return index;
            }
        }

        return -1;
    }

    private static void AppendConcreteOperation(
        StringBuilder sb,
        string padding,
        LuminDataInfo data,
        LuminUnionMemberInfo member,
        DispatchOperation operation,
        string extensionType)
    {
        switch (operation)
        {
            case DispatchOperation.Binary:
                var maxTag = data.UnionMembers.Count == 0 ? 0 : data.UnionMembers.Max(item => item.Id);
                sb.AppendLine(maxTag < 250 && !data.IsWideTag
                    ? $"{padding}writer.WriteUnionHeader({member.Id});"
                    : $"{padding}writer.WriteWideUnionHeader({member.Id});");
                AppendConcreteValueLocal(sb, padding, member);
                sb.AppendLine($"{padding}{extensionType}.WritePolymorphismValue(ref writer, in concreteValue);");
                break;

            case DispatchOperation.Json:
                sb.AppendLine($"{padding}writer.WriteObjectStart();");
                sb.AppendLine($"{padding}if (writer.Option.StringEncoding == global::LuminPack.Option.LuminPackStringEncoding.UTF8)");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.TypeU8);");
                sb.AppendLine($"{padding}else");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.TypeU16);");
                sb.AppendLine($"{padding}writer.WriteInt({member.Id});");
                sb.AppendLine($"{padding}if (writer.Option.StringEncoding == global::LuminPack.Option.LuminPackStringEncoding.UTF8)");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.ValueU8);");
                sb.AppendLine($"{padding}else");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.ValueU16);");
                AppendConcreteValueLocal(sb, padding, member);
                sb.AppendLine($"{padding}{extensionType}.WriteValue(ref writer, in concreteValue);");
                sb.AppendLine($"{padding}writer.WriteObjectEnd();");
                break;

            case DispatchOperation.CalculateOffset:
                sb.AppendLine($"{padding}evaluator.CalculateUnionHeader({member.Id});");
                if (IsConstructedMember(member.Type.OriginalDefinition, member))
                {
                    // The compact slot proves the exact closed type. Reinterpret the local
                    // reference and bind the generated concrete overload statically; this
                    // keeps Cache<T> delegates out of the closed-generic hot path.
                    AppendConcreteValueLocal(sb, padding, member);
                    sb.AppendLine($"{padding}{extensionType}.CalculateOffset(ref evaluator, ref concreteValue);");
                    if (!member.Type.IsValueType)
                    {
                        sb.AppendLine($"{padding}evaluator.Subtract(1);");
                    }
                }
                else if (member.Type.IsUnmanagedType)
                {
                    // A pure unmanaged struct has no normal object header for a union to
                    // replace. Calculate it directly so the union header is retained.
                    sb.AppendLine($"{padding}var concreteValue = this;");
                    sb.AppendLine($"{padding}{extensionType}.CalculateOffset(ref evaluator, ref concreteValue);");
                }
                else
                {
                    // Open generic member: route through the generated generic
                    // CalculateOffset<T> dispatch (typeof chain, JIT-folded for a
                    // closed T), then undo the normal object header that the union
                    // header replaces. No cache, no delegate.
                    sb.AppendLine($"{padding}var concreteValue = this;");
                    sb.AppendLine($"{padding}{extensionType}.CalculateOffset(ref evaluator, ref concreteValue);");
                    sb.AppendLine($"{padding}evaluator.Subtract(1);");
                }
                break;
        }
    }

    private static void AppendConcreteValueLocal(
        StringBuilder sb,
        string padding,
        LuminUnionMemberInfo member)
    {
        var definition = member.Type.OriginalDefinition;
        if (!IsConstructedMember(definition, member))
        {
            sb.AppendLine($"{padding}var concreteValue = this;");
            return;
        }

        var currentType = definition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var memberType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.AppendLine($"{padding}var genericValue = this;");
        sb.AppendLine($"{padding}ref var concreteValue = ref global::LuminPack.Code.LuminPackMarshal.As<{currentType}, {memberType}>(ref genericValue);");
    }

    private static void AppendMethodAttribute(StringBuilder sb, string padding)
    {
        sb.AppendLine($"{padding}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
    }

    private static bool HasDerivedUnionMember(LuminDataInfo data, INamedTypeSymbol definition)
    {
        foreach (var member in data.UnionMembers)
        {
            if (SymbolEqualityComparer.Default.Equals(member.Type.OriginalDefinition, definition))
                continue;

            if (FindMatchedRoot(member.Type, definition) != null)
                return true;
        }

        return false;
    }

    private static INamedTypeSymbol FindMatchedRoot(INamedTypeSymbol member, INamedTypeSymbol root)
    {
        if (member.IsUnboundGenericType)
            member = member.OriginalDefinition;

        if (root.TypeKind == TypeKind.Class)
        {
            for (var current = member.BaseType; current != null; current = current.BaseType)
            {
                if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, root))
                    return current;
            }
        }
        else
        {
            foreach (var current in member.AllInterfaces)
            {
                if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, root))
                    return current;
            }
        }

        return null;
    }

    internal static string GetSlotSuffix(INamedTypeSymbol root)
    {
        var identity = root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        uint hash = 2166136261;
        foreach (var character in identity)
        {
            hash ^= character;
            hash *= 16777619;
        }

        var readableName = new string(identity
            .Where(character => char.IsLetterOrDigit(character) || character == '_')
            .ToArray());
        return $"{readableName}_{hash:x8}";
    }

    private static string SanitizeAssemblyName(string assemblyName)
    {
        var builder = new StringBuilder(assemblyName.Length);
        for (var i = 0; i < assemblyName.Length; i++)
        {
            var character = assemblyName[i];
            if (i == 0 && char.IsDigit(character))
            {
                builder.Append('_');
            }
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        return builder.Length == 0 ? "Assembly" : builder.ToString();
    }

    private static void AppendPartialType(
        StringBuilder sb,
        INamedTypeSymbol type,
        Action<StringBuilder, int> appendBody)
    {
        var namespaceSymbol = type.ContainingNamespace;
        var indent = 0;
        if (namespaceSymbol != null && !namespaceSymbol.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceSymbol.ToDisplayString()}");
            sb.AppendLine("{");
            indent++;
        }

        var typeChain = new List<INamedTypeSymbol>();
        for (var current = type; current != null; current = current.ContainingType)
            typeChain.Insert(0, current);

        foreach (var current in typeChain)
        {
            var padding = new string(' ', indent * 4);
            sb.AppendLine($"{padding}{GetPartialDeclaration(current)}");
            sb.AppendLine($"{padding}{{");
            indent++;
        }

        appendBody(sb, indent);

        for (var i = typeChain.Count - 1; i >= 0; i--)
        {
            indent--;
            sb.AppendLine($"{new string(' ', indent * 4)}}}");
        }

        if (namespaceSymbol != null && !namespaceSymbol.IsGlobalNamespace)
            sb.AppendLine("}");

        sb.AppendLine();
    }

    private static string GetPartialDeclaration(INamedTypeSymbol type)
    {
        var declaration = new StringBuilder();
        var accessibility = GetAccessibility(type.DeclaredAccessibility);
        if (accessibility.Length != 0)
            declaration.Append(accessibility).Append(' ');

        if (type.IsStatic)
            declaration.Append("static ");
        else if (type.TypeKind == TypeKind.Struct)
        {
            if (type.IsRefLikeType)
                declaration.Append("ref ");
            if (type.IsReadOnly)
                declaration.Append("readonly ");
        }

        declaration.Append("partial ");
        if (type.IsRecord)
            declaration.Append(type.TypeKind == TypeKind.Struct ? "record struct " : "record class ");
        else
            declaration.Append(type.TypeKind == TypeKind.Interface ? "interface " :
                type.TypeKind == TypeKind.Struct ? "struct " : "class ");

        declaration.Append(EscapeIdentifier(type.Name));
        if (type.TypeParameters.Length != 0)
        {
            declaration.Append('<');
            declaration.Append(string.Join(", ", type.TypeParameters.Select(parameter => EscapeIdentifier(parameter.Name))));
            declaration.Append('>');
        }

        return declaration.ToString();
    }

    private static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => string.Empty,
    };

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;

    private enum DispatchOperation
    {
        Binary,
        Json,
        CalculateOffset,
    }
}
