using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using LuminPack.SourceGenerator;

namespace LuminPack.Code.Core;

internal static class LuminPackUnionDispatchCodeGenerator
{
    public static string Generate(LuminDataInfo data, Compilation compilation)
    {
        if (!data.isUnion || !data.CanGenerateUnionDispatch || data.TypeSymbol == null)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var root = data.TypeSymbol.OriginalDefinition;
        var suffix = GetSlotSuffix(root);
        var extensionType = "global::LuminPack.Generated.LuminPackExtensions_" +
            SanitizeAssemblyName(compilation.AssemblyName ?? "Assembly");
        AppendPartialType(sb, root, (builder, indent) =>
            AppendRootMethods(builder, indent, root, suffix));

        foreach (var group in data.UnionMembers
                     .Where(member => IsFastPathMember(data, member))
                     .GroupBy(member => member.Type.OriginalDefinition, SymbolEqualityComparer.Default))
        {
            var members = group.ToList();
            var definition = members[0].Type.OriginalDefinition;
            var matchedRoot = FindMatchedRoot(definition, root);
            if (matchedRoot == null)
                continue;

            AppendPartialType(sb, definition, (builder, indent) =>
                AppendMemberMethods(builder, indent, data, root, matchedRoot, members, suffix, extensionType));
        }

        return sb.ToString();
    }

    internal static bool IsFastPathMember(LuminDataInfo data, LuminUnionMemberInfo member)
    {
        if (!data.CanGenerateUnionDispatch || !member.CanGenerateDispatch)
            return false;

        return FindMatchedRoot(member.Type.OriginalDefinition, data.TypeSymbol.OriginalDefinition) != null;
    }

    private static void AppendRootMethods(
        StringBuilder sb,
        int indent,
        INamedTypeSymbol root,
        string suffix)
    {
        var padding = new string(' ', indent * 4);
        var rootType = root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var modifier = root.TypeKind == TypeKind.Interface ? string.Empty : "internal virtual ";

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{modifier}void __LuminPackUnionSerialize_{suffix}(ref global::LuminPack.Core.LuminPackWriter writer)");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(((object)this).GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{modifier}void __LuminPackUnionSerializeJson_{suffix}(ref global::LuminPack.Core.LuminPackJsonWriter writer)");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(((object)this).GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{modifier}void __LuminPackUnionCalculateOffset_{suffix}(ref global::LuminPack.Core.LuminPackEvaluator evaluator)");
        sb.AppendLine($"{padding}{{");
        sb.AppendLine($"{padding}    global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(((object)this).GetType(), typeof({rootType}));");
        sb.AppendLine($"{padding}}}");
    }

    private static void AppendMemberMethods(
        StringBuilder sb,
        int indent,
        LuminDataInfo data,
        INamedTypeSymbol root,
        INamedTypeSymbol matchedRoot,
        IReadOnlyList<LuminUnionMemberInfo> members,
        string suffix,
        string extensionType)
    {
        var padding = new string(' ', indent * 4);
        var bodyPadding = new string(' ', (indent + 1) * 4);
        var rootType = matchedRoot.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var isInterface = root.TypeKind == TypeKind.Interface;
        var prefix = isInterface ? $"void {rootType}." : "internal override void ";

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{prefix}__LuminPackUnionSerialize_{suffix}(ref global::LuminPack.Core.LuminPackWriter writer)");
        sb.AppendLine($"{padding}{{");
        AppendMemberDispatchBody(sb, bodyPadding, data, members, rootType, DispatchOperation.Binary, extensionType);
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{prefix}__LuminPackUnionSerializeJson_{suffix}(ref global::LuminPack.Core.LuminPackJsonWriter writer)");
        sb.AppendLine($"{padding}{{");
        AppendMemberDispatchBody(sb, bodyPadding, data, members, rootType, DispatchOperation.Json, extensionType);
        sb.AppendLine($"{padding}}}");
        sb.AppendLine();

        AppendMethodAttribute(sb, padding);
        sb.AppendLine($"{padding}{prefix}__LuminPackUnionCalculateOffset_{suffix}(ref global::LuminPack.Core.LuminPackEvaluator evaluator)");
        sb.AppendLine($"{padding}{{");
        AppendMemberDispatchBody(sb, bodyPadding, data, members, rootType, DispatchOperation.CalculateOffset, extensionType);
        sb.AppendLine($"{padding}}}");
    }

    private static void AppendMemberDispatchBody(
        StringBuilder sb,
        string padding,
        LuminDataInfo data,
        IReadOnlyList<LuminUnionMemberInfo> members,
        string rootType,
        DispatchOperation operation,
        string extensionType)
    {
        var definition = members[0].Type.OriginalDefinition;
        var constructedMembers = members
            .Where(member => !SymbolEqualityComparer.Default.Equals(member.Type, definition) &&
                             !member.Type.IsUnboundGenericType)
            .ToList();
        var openMember = members.FirstOrDefault(member =>
            SymbolEqualityComparer.Default.Equals(member.Type, definition) || member.Type.IsUnboundGenericType);

        foreach (var member in constructedMembers)
        {
            var condition = GetConstructedTypeCondition(definition, member.Type);
            sb.AppendLine($"{padding}if ({condition})");
            sb.AppendLine($"{padding}{{");
            AppendConcreteOperation(sb, padding + "    ", data, member, operation, extensionType);
            sb.AppendLine($"{padding}    return;");
            sb.AppendLine($"{padding}}}");
        }

        if (openMember.Type != null)
        {
            AppendConcreteOperation(sb, padding, data, openMember, operation, extensionType);
            return;
        }

        sb.AppendLine($"{padding}global::LuminPack.Code.LuminPackExceptionHelper.ThrowNotFoundInUnionType(GetType(), typeof({rootType}));");
    }

    private static void AppendConcreteOperation(
        StringBuilder sb,
        string padding,
        LuminDataInfo data,
        LuminUnionMemberInfo member,
        DispatchOperation operation,
        string extensionType)
    {
        switch (operation)
        {
            case DispatchOperation.Binary:
                var maxTag = data.UnionMembers.Count == 0 ? 0 : data.UnionMembers.Max(item => item.Id);
                sb.AppendLine(maxTag < 250 && !data.IsWideTag
                    ? $"{padding}writer.WriteUnionHeader({member.Id});"
                    : $"{padding}writer.WriteWideUnionHeader({member.Id});");
                sb.AppendLine($"{padding}var concreteValue = this;");
                sb.AppendLine($"{padding}{extensionType}.WritePolymorphismValue(ref writer, in concreteValue);");
                break;

            case DispatchOperation.Json:
                sb.AppendLine($"{padding}writer.WriteObjectStart();");
                sb.AppendLine($"{padding}if (writer.Option.StringEncoding == global::LuminPack.Option.LuminPackStringEncoding.UTF8)");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.TypeU8);");
                sb.AppendLine($"{padding}else");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.TypeU16);");
                sb.AppendLine($"{padding}writer.WriteInt({member.Id});");
                sb.AppendLine($"{padding}if (writer.Option.StringEncoding == global::LuminPack.Option.LuminPackStringEncoding.UTF8)");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.ValueU8);");
                sb.AppendLine($"{padding}else");
                sb.AppendLine($"{padding}    writer.WritePropertyName(global::LuminPack.LuminPackConstUtf8.ValueU16);");
                sb.AppendLine($"{padding}var concreteValue = this;");
                sb.AppendLine($"{padding}{extensionType}.WriteValue(ref writer, in concreteValue);");
                sb.AppendLine($"{padding}writer.WriteObjectEnd();");
                break;

            case DispatchOperation.CalculateOffset:
                sb.AppendLine($"{padding}evaluator.CalculateUnionHeader({member.Id});");
                if (member.Type.IsUnmanagedType)
                {
                    // A pure unmanaged struct has no normal object header for a union to
                    // replace. Calculate it directly so the union header is retained.
                    sb.AppendLine($"{padding}var concreteValue = this;");
                    sb.AppendLine($"{padding}{extensionType}.CalculateOffset(ref evaluator, ref concreteValue);");
                }
                else
                {
                    sb.AppendLine($"{padding}evaluator.CalculatePolymorphismValue(this);");
                }
                break;
        }
    }

    private static string GetConstructedTypeCondition(INamedTypeSymbol definition, INamedTypeSymbol constructed)
    {
        var conditions = new List<string>();
        for (var i = 0; i < definition.TypeParameters.Length; i++)
        {
            var parameter = EscapeIdentifier(definition.TypeParameters[i].Name);
            var argument = constructed.TypeArguments[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            conditions.Add($"typeof({parameter}) == typeof({argument})");
        }

        return conditions.Count == 0 ? "true" : string.Join(" && ", conditions);
    }

    private static void AppendMethodAttribute(StringBuilder sb, string padding)
    {
        sb.AppendLine($"{padding}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
    }

    private static INamedTypeSymbol FindMatchedRoot(INamedTypeSymbol member, INamedTypeSymbol root)
    {
        if (member.IsUnboundGenericType)
            member = member.OriginalDefinition;

        if (root.TypeKind == TypeKind.Class)
        {
            for (var current = member.BaseType; current != null; current = current.BaseType)
            {
                if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, root))
                    return current;
            }
        }
        else
        {
            foreach (var current in member.AllInterfaces)
            {
                if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, root))
                    return current;
            }
        }

        return null;
    }

    internal static string GetSlotSuffix(INamedTypeSymbol root)
    {
        var identity = root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        uint hash = 2166136261;
        foreach (var character in identity)
        {
            hash ^= character;
            hash *= 16777619;
        }

        var readableName = new string(identity
            .Where(character => char.IsLetterOrDigit(character) || character == '_')
            .ToArray());
        return $"{readableName}_{hash:x8}";
    }

    private static string SanitizeAssemblyName(string assemblyName)
    {
        var builder = new StringBuilder(assemblyName.Length);
        for (var i = 0; i < assemblyName.Length; i++)
        {
            var character = assemblyName[i];
            if (i == 0 && char.IsDigit(character))
            {
                builder.Append('_');
            }
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        return builder.Length == 0 ? "Assembly" : builder.ToString();
    }

    private static void AppendPartialType(
        StringBuilder sb,
        INamedTypeSymbol type,
        Action<StringBuilder, int> appendBody)
    {
        var namespaceSymbol = type.ContainingNamespace;
        var indent = 0;
        if (namespaceSymbol != null && !namespaceSymbol.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceSymbol.ToDisplayString()}");
            sb.AppendLine("{");
            indent++;
        }

        var typeChain = new List<INamedTypeSymbol>();
        for (var current = type; current != null; current = current.ContainingType)
            typeChain.Insert(0, current);

        foreach (var current in typeChain)
        {
            var padding = new string(' ', indent * 4);
            sb.AppendLine($"{padding}{GetPartialDeclaration(current)}");
            sb.AppendLine($"{padding}{{");
            indent++;
        }

        appendBody(sb, indent);

        for (var i = typeChain.Count - 1; i >= 0; i--)
        {
            indent--;
            sb.AppendLine($"{new string(' ', indent * 4)}}}");
        }

        if (namespaceSymbol != null && !namespaceSymbol.IsGlobalNamespace)
            sb.AppendLine("}");

        sb.AppendLine();
    }

    private static string GetPartialDeclaration(INamedTypeSymbol type)
    {
        var declaration = new StringBuilder();
        var accessibility = GetAccessibility(type.DeclaredAccessibility);
        if (accessibility.Length != 0)
            declaration.Append(accessibility).Append(' ');

        if (type.IsStatic)
            declaration.Append("static ");
        else if (type.TypeKind == TypeKind.Struct)
        {
            if (type.IsRefLikeType)
                declaration.Append("ref ");
            if (type.IsReadOnly)
                declaration.Append("readonly ");
        }

        declaration.Append("partial ");
        if (type.IsRecord)
            declaration.Append(type.TypeKind == TypeKind.Struct ? "record struct " : "record class ");
        else
            declaration.Append(type.TypeKind == TypeKind.Interface ? "interface " :
                type.TypeKind == TypeKind.Struct ? "struct " : "class ");

        declaration.Append(EscapeIdentifier(type.Name));
        if (type.TypeParameters.Length != 0)
        {
            declaration.Append('<');
            declaration.Append(string.Join(", ", type.TypeParameters.Select(parameter => EscapeIdentifier(parameter.Name))));
            declaration.Append('>');
        }

        return declaration.ToString();
    }

    private static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => string.Empty,
    };

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;

    private enum DispatchOperation
    {
        Binary,
        Json,
        CalculateOffset,
    }
}
